language: node_js
node_js:
    - "5"
script:
    - node_modules/.bin/grunt ts
    - node_modules/.bin/knex --knexfile js/knex/knexfile.js migrate:latest --env database
    - node_modules/.bin/grunt mocha_istanbul
    - node_modules/.bin/grunt coveralls
notifications:
    slack: vyrent:9ZjlfCRjtmI8UTjIVgo847nC
